name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches: "master"
jobs:
# The job below generates the images displayed on lowlighter/lowlighter
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: JayantGoel001/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_music: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: no
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          
      - name: Personal metrics (detailed)
        uses: JayantGoel001/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
#           plugin_pagespeed: yes
#           plugin_pagespeed_detailed: yes
#           plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_followup: yes
          plugin_languages: yes
          plugins_errors_fatal: yes
          
